# https_dns_proxy 配置文件
# 这是注释行

# 监听设置
listen_addr = 127.0.0.1
listen_port = 5053
tcp_client_limit = 50

# 进程设置
daemonize = no
user = 
group = 

# DNS 引导设置
bootstrap_dns = 8.8.8.8,1.1.1.1,9.9.9.9
fallback_dns = 8.8.8.8,4.4.4.4
polling_interval = 3600
ipv4_only = no

# DoH 服务器设置
resolver_url = https://dns.google/dns-query
# resolver_url = https://localhost:8053/dns-query
http_version = 2
max_idle_time = 300
conn_loss_time = 5

# 网络设置
dscp = 0
proxy =
source_addr =
#ca_info = /etc/ssl/certs/ca-certificates.crt
#ca_info = /studio/OpenSource/doh/https_dns_proxy/tests/simulation-test/server.crt


# 日志设置
loglevel = info
use_syslog = no
logfile =
stats_interval = 0
flight_recorder = 1000


